export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';
export const UPDATE_DIMENSIONS = 'UPDATE_DIMENSIONS';
export const UPDATE_COINS = 'UPDATE_COINS';
export const UPDATE_SELECTED_MEMBER = 'UPDATE_SELECTED_MEMBER';
